{{ if ne (len .Values.registry.proxyCache) 0 }}
{{- range $index, $proxyCache := .Values.registry.proxyCache }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.registry" $ }}-{{ $index }}"
  labels:
{{ include "harbor.labels" $ | indent 4 }}
spec:
  ports:
    - name: registry
      port: 5000
  selector:
{{ include "harbor.matchLabels" $ | indent 4 }}
    component: registry-proxy
    index: "{{ $index }}"
{{- end }}
{{ end }}