{{ if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-nginx"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: nginx
{{ end }}
