{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.ingress.core" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  {{- if .Values.expose.tls.enabled }}
  tls:
  - secretName: {{ template "harbor.certificate-secret" . }}
    {{- if $ingress.host }}
    hosts: 
    - {{ $ingress.host }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /registry
        backend:
          serviceName: {{ template "harbor.portal" . }}
          servicePort: 80
      - path: /registry/api/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /registry/service/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /v2/
        backend:
          serviceName: {{ template "harbor.proxy" . }}
          servicePort: 80
      - path: /registry/chartrepo/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /registry/c/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      # - path: /registry/
      #   backend:
      #     serviceName: {{ template "harbor.proxy" . }}
      #     servicePort: 80
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
{{- end }}