apiVersion: v1
data:
  config.yml: |-
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /storage
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
      redirect:
        disable: false
    http:
      addr: :5000
      # set via environment variable
      # secret: placeholder
      debug:
        addr: localhost:5001
    validation:
      disabled: true
    proxy:
      remoteurl: https://r.lawr.ink
kind: ConfigMap
metadata:
  name: registry-cm

