apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "local-cache-registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "local-cache-registry.name" . }}
    helm.sh/chart: {{ include "local-cache-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "local-cache-registry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "local-cache-registry.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SSL_CERT_DIR
            value: /etc/ssl/certs
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
          - mountPath: etc/docker/registry/config.yml
            name: config
            subPath: config.yml
          - mountPath: /etc/ssl/certs
            name: ca
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - configMap:
          defaultMode: 256
          items:
          - key: config.yml
            path: config.yml
          name: registry-cm
          optional: false
        name: config
      - name: ca
        hostPath:
          path: /etc/docker/certs.d/r.lawr.ink
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
