apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-cattle-global-data-local-proxy
  name: local-proxy
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-cattle-global-data-local-proxy
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-cattle-global-data-local-proxy
    spec:
      containers:
      - image: nginx
        name: local-proxy
        ports:
        - containerPort: 80
          name: 80tcp01
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: config
          subPath: default.conf
      volumes:
      - configMap:
          defaultMode: 256
          items:
          - key: default.conf
            path: default.conf
          name: nginx-cm
          optional: false
        name: config
