apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: {{ include "local-cache-registry.name" . }}
    helm.sh/chart: {{ include "local-cache-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "local-cache-registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
