apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: query
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thanos.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: query
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - query
          {{- range $clusterId := (split ":" .Values.clusterIds) }}
          - --store
          - "{{ $clusterId }}:80"
          {{- end }}
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: nginx
          image: nginx
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-config
            subPath: default.conf
          {{- if .Values.privateCa }}
          - mountPath: /etc/kubernetes/ssl/certs
            name: ca-cert
          {{- end }}
      hostAliases:
      {{- if .Values.clusterIds }}
      - hostnames:
      {{- range $clusterId := (split ":" .Values.clusterIds) }}
        - {{ $clusterId }}
      {{- end }}
        ip: 127.0.0.1
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - configMap:
          items:
          - key: default.conf
            path: default.conf
          name: {{ include "thanos.fullname" . }}-nginx-configmap
        name: nginx-config
      {{- if .Values.privateCa }}
      - name: ca-cert
        hostPath:
          path: /etc/kubernetes/ssl/certs
      {{- end }}
