apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  all.yaml: |-
    - name: RANCHER_MONITORING
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 0 #never
      options:
        path: /var/lib/grafana/dashboards
  datasources.yaml: |-
    apiVersion: 1

    datasources:
    - name: RANCHER_MONITORING
      type: prometheus
      access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      url: http://{{ include "thanos.fullname" . }}
{{ (.Files.Glob "dashboards/*.json").AsConfig | indent 2 }}
