apiVersion: v1
kind: Service
metadata:
  name: access-thanos
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: query
    kubernetes.io/cluster-service: "true"
spec:
  type: {{ .Values.thanos.service.type }}
  ports:
    - port: {{ .Values.thanos.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
    component: query
