{{- if or .Values.thanos.store.enabled .Values.thanos.compact.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: objstore-config-{{ .Release.Name }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
  config.yaml: |-
{{ toYaml .Values.thanos.objectConfig | indent 6 }}
{{- end }}