apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-{{ .Release.Name }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: query
spec:
  replicas: {{ .Values.thanos.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
      component: query
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
        component: query
    spec:
      containers:
        - name: thanos
          image: "{{ .Values.thanos.image.repository }}:{{ .Values.thanos.image.tag }}"
          imagePullPolicy: {{ .Values.thanos.image.pullPolicy }}
          args:
          - query
          {{- range $clusterId := (split ":" .Values.clusterIds) }}
          - --store
          - "{{ $clusterId }}:80"
          {{- end }}
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.thanos.resources.thanos | nindent 12 }}
        - name: nginx
          image: "{{ .Values.thanos.image.proxy.repository }}:{{ .Values.thanos.image.proxy.tag }}"
          imagePullPolicy: {{ .Values.thanos.image.pullPolicy }}
          resources:
            {{- toYaml .Values.thanos.resources.proxy | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-config
            subPath: default.conf
          {{- if .Values.privateCa }}
          - mountPath: /etc/kubernetes/ssl/certs
            name: ca-cert
          {{- end }}
      hostAliases:
      {{- if .Values.clusterIds }}
      - hostnames:
      {{- range $clusterId := (split ":" .Values.clusterIds) }}
        - {{ $clusterId }}
      {{- end }}
        ip: 127.0.0.1
      {{- end }}
      nodeSelector:
      {{- include "linux-node-selector" . | nindent 8 }}
      {{- with .Values.thanos.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.thanos.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- include "linux-node-tolerations" . | nindent 8 }}
      {{- with .Values.thanos.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          items:
          - key: default.conf
            path: default.conf
          name: proxy-{{ .Release.Name }}
        name: nginx-config
      {{- if .Values.privateCa }}
      - name: ca-cert
        hostPath:
          path: /etc/kubernetes/ssl/certs
      {{- end }}
