{
 "title": "Rancher Global Monitoring",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(node_load1, prometheus_from)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (prometheus_from) (up{prometheus_from=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_info{prometheus_from=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info{prometheus_from=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", prometheus_from=~\"$cluster\"}[5m])) by (prometheus_from))",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes{prometheus_from=~\"$cluster\"}) by (prometheus_from) / sum(node_memory_MemTotal_bytes{prometheus_from=~\"$cluster\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\", prometheus_from=~\"$cluster\"}) by (prometheus_from) - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\", prometheus_from=~\"$cluster\"}) by (prometheus_from)) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\", prometheus_from=~\"$cluster\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  { "title": "Cluster Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "ETCD DB Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{prometheus_from=~\"$cluster\"}",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "ETCD Leader Election",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{prometheus_from=~\"$cluster\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "API Server Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_sum{prometheus_from=~\"$cluster\"} / apiserver_request_latencies_count{prometheus_from=~\"$cluster\"}) by (instance, prometheus_from) /1e+06",
     "legendFormat": "{{prometheus_from}}/{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Response",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code!=\"0\", prometheus_from=~\"$cluster\"}[5m])) by (instance, code, prometheus_from)",
     "legendFormat": "{{prometheus_from}}/{{instance}}/{{code}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Node Network Receive Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (prometheus_from, node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Network Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) by (prometheus_from, node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Read Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m])) by (node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Write Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m])) by (prometheus_from, node)",
     "legendFormat": "{{prometheus_from}}/{{node}}"
    }
   ]
  },
  { "title": "Workload Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Unhealthy Pod Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\", prometheus_from=~\"$cluster\"}) by (prometheus_from) - sum(kube_pod_status_phase{phase=\"Succeeded\", prometheus_from=~\"$cluster\"}) by (prometheus_from) + sum(kube_pod_status_unschedulable{prometheus_from=~\"$cluster\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Unschedulable Pod Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{condition=\"false\", prometheus_from=~\"$cluster\"}) by (prometheus_from)",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Pod Restart Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(increase(kube_pod_container_status_restarts_total{prometheus_from=~\"$cluster\"}[5m])) by (prometheus_from))",
     "legendFormat": "{{prometheus_from}}"
    }
   ]
  },
  {
   "title": "Container CPU Reservation (core)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Reservation (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes / 1024 / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (core)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name!=\"\"}[5m])) by (prometheus_from, namespace, pod_name)",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod!=\"\"}) by (prometheus_from, namespace, pod) / 1024 / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Receive Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod!=\"\"}[5m])) by (prometheus_from, namespace, pod) / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Transmit Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod!=\"\"}[5m])) by (prometheus_from, namespace, pod) / 1024",
     "legendFormat": "{{prometheus_from}}/{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}