{{- if eq .Values.expose.type "ingress" -}}
{{- if eq .Values.expose.tls.type "letsEncrypt" -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: "{{ template "harbor.ingress" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  acme:
    {{- if eq .Values.expose.letsEncrypt.environment "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    {{- if eq .Values.expose.letsEncrypt.environment "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.expose.letsEncrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.expose.letsEncrypt.environment }}
    http01: {}
{{- end -}}
{{- end -}}
