{{- if and (eq .Values.expose.type "ingress") (eq .Values.expose.tls.type "rancher") -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: "{{ template "harbor.ingress" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ca:
    secretName: tls-rancher
{{- end -}}
